name: Update Docs Branch
on:
  push:
    branches: [main]

jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      deployments: read
      packages: none
      pull-requests: write
      security-events: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Git User
        run: |
          git config user.name "GitHub Action"
          git config user.email "leestott@microsoft.com"

      - name: Update Docs Branch
        run: |
          git fetch origin
          git checkout docs
          git pull
          git merge origin/main
          git push origin docs
